title: Portf0lio
logo: assets/img/icon/icon.svg
description: Showcasing grounds for my work. If you want to see my other work go [here](https://www.instagram.com/jjclucio)
show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
